#!/bin/bash
# Configure Xcode project signing identity for a known publisher.
#
# Usage:
#   ./ios/configure_identity.sh yunxiang
#   ./ios/configure_identity.sh yao
#   ./ios/configure_identity.sh --team-id ABCD1234EF --bundle-id com.example.ash
#
# Writes ios/Flutter/Identity.xcconfig with local signing values. The file is
# intentionally ignored so the tracked Xcode project stays valid and clean.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
IDENTITY_CONFIG="$SCRIPT_DIR/Flutter/Identity.xcconfig"

# --- Parse arguments ---
TEAM_ID=""
BUNDLE_ID=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --team-id)
      if [[ $# -lt 2 ]]; then
        echo "Error: --team-id requires a value" >&2
        exit 1
      fi
      TEAM_ID="$2"
      shift 2
      ;;
    --bundle-id)
      if [[ $# -lt 2 ]]; then
        echo "Error: --bundle-id requires a value" >&2
        exit 1
      fi
      BUNDLE_ID="$2"
      shift 2
      ;;
    -*)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
    *)
      # Positional arg = publisher nickname
      case "$1" in
        yunxiang)
          TEAM_ID="DJD849Y8Q6"
          BUNDLE_ID="com.yunxiang.ash"
          ;;
        yao)
          TEAM_ID="V9Q67SYWWQ"
          BUNDLE_ID="com.yao.ash"
          ;;
        *)
          echo "Error: unknown publisher '$1'" >&2
          echo "Known publishers: yao, yunxiang" >&2
          exit 1
          ;;
      esac
      shift
      ;;
  esac
done

if [[ -z "$TEAM_ID" || -z "$BUNDLE_ID" ]]; then
  echo "Usage: $0 <publisher-nickname>" >&2
  echo "       $0 --team-id <ID> --bundle-id <bundle>" >&2
  echo "" >&2
  echo "Known publishers: yao, yunxiang" >&2
  exit 1
fi

if [[ ! "$TEAM_ID" =~ ^[A-Z0-9]+$ ]]; then
  echo "Error: team id must contain only uppercase letters and digits" >&2
  exit 1
fi

if [[ ! "$BUNDLE_ID" =~ ^[A-Za-z0-9.-]+$ ]]; then
  echo "Error: bundle id must contain only letters, digits, dots, and hyphens" >&2
  exit 1
fi

mkdir -p "$(dirname "$IDENTITY_CONFIG")"

{
  echo "// Generated by ios/configure_identity.sh. Do not commit."
  echo "ASH_DEVELOPMENT_TEAM = $TEAM_ID"
  echo "ASH_BUNDLE_IDENTIFIER = $BUNDLE_ID"
} > "$IDENTITY_CONFIG"

echo "Done. Wrote signing identity to $IDENTITY_CONFIG"
